[package]
name = "splice-bin"
version = "0.3.0"
edition = "2021"
description = "Splice Protocol - Binary"

[[bin]]
name = "splice"
path = "src/main.rs"

[dependencies]
splice = { path = "../splice" }
tokio = { workspace = true, features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
uuid = { version = "1.0", features = ["v4"] }
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
